name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@huggingface.co"
          git config --global user.name "HF Sync Bot"

          mkdir ../clean_code
          rsync -av . ../clean_code --exclude .git --exclude .github
          
          cd ../clean_code
          rm -rf docs/images/
          rm -f frontend/public/logo.png
          rm -f mm_facetoface_collect_qrcode_1775206373527.png
          rm -f kiro_*.png
          
          git init
          git add .
          git commit -m "Initial clean sync without binaries"
          
          # Đổi tên nhánh thành main để khớp với Hugging Face
          git branch -M main 
          
          git push --force https://thienphung123:$HF_TOKEN@huggingface.co/spaces/thienphung123/quan-ly-affiliate-ai main
